# **Scalar, Vector and Matrix:**

> ![](https://th.bing.com/th/id/R.9948aa39a95c784dd7283c337d0d95c1?rik=m6fMuTEoPirB6w&pid=ImgRaw&r=0)

## **1. Scalar:**

A scalar is a single numerical value - essentially just a regular number. It's the most basic mathematical object, representing a quantity with magnitude but no direction, unlike vectors which have both magnitude and direction, or matrices which are arrays of numbers.

Scalars are typically denoted using lowercase letters, often in italics:
   
   - *a*, *b*, *c*, *x*, *y*, *z*
   
   - Greek letters: *$α$* (alpha), *$β$* (beta), *$λ$* (lambda)
   
   - Sometimes with subscripts: *$a₁$*, *$a₂$*, *$x₀$*

In mathematical contexts, scalars are usually written in italics to distinguish them from vectors (bold lowercase) and matrices (bold uppercase).

### **Usefulness in Deep Learning:**

**Scalars play crucial roles in deep learning:**

1. **`Learning Rate`**: Perhaps the most important scalar hyperparameter, controlling how much model parameters are updated during training. A learning rate of 0.001 means parameters are adjusted by small increments.

2. **`Loss Values`**: The output of loss functions are scalars representing how well the model is performing. During training, we minimize these scalar values.

3. **`Regularization Parameters`**: Lambda values in $L1/L2$ regularization are scalars that control the strength of regularization applied to prevent overfitting.

4. **`Batch Size and Epochs`**: These are scalar hyperparameters that determine training behavior - how many samples to process at once and how many times to iterate through the dataset.

5. **`Activation Function Parameters`**: Some activation functions use scalar parameters, like the alpha parameter in LeakyReLU or the beta parameter in Swish.

6. **`Temperature in Softmax`**: A scalar parameter that controls the "sharpness" of probability distributions in classification tasks.

### **Defining Scalars in PyTorch:**

**PyTorch provides several ways to create and work with scalars:**

In [ ]:
import torch

# Creating scalars
scalar1 = torch.tensor(3.14)           # Float scalar
scalar2 = torch.tensor(42)             # Integer scalar
scalar3 = torch.tensor(2.0, dtype=torch.float32)  # Explicit dtype
print(f"Scalar-1: {scalar1}")
print(f"Scalar-2: {scalar2}")
print(f"Scalar-3: {scalar3}")
# Creating scalars on GPU
# scalar_gpu = torch.tensor(5.0, device='cuda')

# Creating scalars that require gradients (for optimization)
learning_rate = torch.tensor(0.01, requires_grad=True)
print(f"Learning Rate: {learning_rate}")

# Using scalar operations
loss = torch.tensor(0.5, requires_grad=True)
print(f"Loss: {loss}")
scaled_loss = loss * 2.0  # Scalar multiplication
print(f"Scaled Loss: {scaled_loss}")

# Converting Python numbers to tensors
python_num = 3.14
print(f"Python umber: {python_num}")
tensor_scalar = torch.tensor(python_num)
print(f"Tensor Scalar: {tensor_scalar}")
# Extracting scalar values
scalar_value = tensor_scalar.item()  # Returns Python number
print(f"Scalaed Value: {scaled_loss}")

Scalar-1: 3.140000104904175
Scalar-2: 42
Scalar-3: 2.0
Learning Rate: 0.009999999776482582
Loss: 0.5
Scaled Loss: 1.0
Python umber: 3.14
Tensor Scalar: 3.140000104904175
Scalaed Value: 1.0


### **Properties of Scalars:**

1. **`Commutativity`**:    
   
   Scalar operations are commutative, meaning *$a + b = b + a$* and *$a × b = b × a$*. This property doesn't hold for matrix operations.

2. **`Associativity`**: 

   For scalars, *$(a + b) + c = a + (b + c)$* and *$(a × b) × c = a × (b × c)$*. This allows flexible grouping in calculations.

3. **`Distributivity`**:   
   
   Scalars distribute over addition: *$a × (b + c) = a × b + a × c$*. This property is fundamental in expanding algebraic expressions.

4. **`Identity Elements`**:    
   
   The additive identity is 0 (*$a + 0 = a$*) and the multiplicative identity is 1 (*$a × 1 = a$*). These are crucial for maintaining values during operations.

5. **`Inverse Elements`**:    

   Every scalar *$a$* has an additive inverse *$-a$* such that *$a + (-a) = 0$*, and every non-zero scalar has a multiplicative inverse *$1/a$* such that *$a × (1/a) = 1$*.

6. **`Scalar Multiplication with Vectors`**:   
   
   When multiplying a scalar with a vector, the scalar multiplies each component of the vector: *$c × [x, y, z] = [c×x, c×y, c×z]$*. This scales the vector's magnitude while preserving its direction.

7. **`Scalar Multiplication with Matrices`**:    
   
   Similarly, scalar multiplication with matrices multiplies each element: *$c × [[a, b], [c, d]] = [[c×a, c×b], [c×c, c×d]]$*.

8.  **`Field Properties`**:    
   Scalars typically come from a field (like real numbers $ℝ$ or complex numbers $ℂ$), which means they satisfy all the algebraic properties mentioned above. This mathematical structure is what makes linear algebra operations well-defined and consistent.

9. **`Dimension`**:   
    
   Scalars are zero-dimensional objects - they have no spatial extent, unlike vectors (1D), matrices (2D), or higher-order tensors.

10. **`Invariance`**:   
  Scalars remain unchanged under coordinate transformations. While vectors and matrices can change representation when you rotate or translate coordinate systems, scalars maintain their value.

These properties make scalars the foundation for more complex linear algebra operations and are essential for understanding how deep learning algorithms manipulate data through mathematical transformations.

-------------
-------------
---------------

## **Number Sets:**


**1. Natural Numbers (ℕ):**
   - **Values**: {1, 2, 3, 4, 5, 6, ...}
   - **Description**: Positive counting numbers, sometimes includes 0 depending on context

**2. Whole Numbers (𝕎):** 
  - **Values**: {0, 1, 2, 3, 4, 5, ...}
  - **Description**: Natural numbers plus zero

**3. Integers (ℤ):**
  - **Values**: {..., -3, -2, -1, 0, 1, 2, 3, ...}
  - **Description**: Whole numbers plus negative numbers

**4. Rational Numbers (ℚ):**
  - **Values**: All fractions p/q where p, q are integers and q ≠ 0
  - **Examples**: 1/2, -3/4, 5, 0.25, 0.333..., -2.5
  - **Description**: Numbers that can be expressed as fractions

**5. Irrational Numbers:**
  - **Values**: Numbers that cannot be expressed as fractions
  - **Examples**: π, e, √2, √3, φ (golden ratio)
  - **Description**: Non-repeating, non-terminating decimals

**6. Real Numbers (ℝ):**  
  - **Values**: All rational and irrational numbers combined
  - **Description**: All numbers on the number line, includes everything above

**7. Complex Numbers (ℂ):**
  - **Values**: Numbers of the form a + bi where a, b are real and i = √(-1)
  - **Examples**: 3 + 4i, -2 - 5i, 7 (pure real), 3i (pure imaginary)
  - **Description**: Includes real numbers plus imaginary numbers

**Quick Memory Aid:**
> $ℕ ⊂ 𝕎 ⊂ ℤ ⊂ ℚ ⊂ ℝ ⊂ ℂ$

-----
-----------
--------------

## **2. Vectors:**

> ![](https://cdn1.byjus.com/wp-content/uploads/2021/03/Vector.png)

A vector is an ordered collection of numbers (called `components` or `elements`) that represents a quantity with `both magnitude and direction`. Unlike scalars which are just single numbers, vectors contain multiple values and can represent `points in space`, `directions`, or `collections of related data`.

**Representation and Notation:**

**Mathematical Notation**:
   - **Bold lowercase letters**: **$v$**, **$u$**, **$a$**, **$x$**

   - **Arrows**: v⃗, u⃗, a⃗

   - **Component form**: $v = [v₁, v₂, v₃]$ or $v = (v₁, v₂, v₃)$
   
   - **Column vector**: 
  ```raw
        v = [v₁]
            [v₂]
            [v₃]
  ```

**Common Representations**:
   - **2D vector**: $v = [3, 4]$ represents a point at coordinates $(3, 4)$

   - **3D vector**: $v = [1, -2, 5]$ represents a point in $3D$ space

   - **n-dimensional**: $v = [v₁, v₂, ..., vₙ]$ for high-dimensional spaces

### **Geometric and Linear Algebraic Meanings:**

**1. Geometric Interpretation**:  
   - Vectors represent arrows in space with specific direction and magnitude. 
   
   - A vector $[3, 4]$ can be visualized as an arrow starting from the origin $(0, 0)$ and pointing to the coordinate $(3, 4)$. 
   
   - The length of this arrow is the magnitude $√(3² + 4²) = 5$, and it points in a specific direction from the origin.

**2. Linear Algebraic Interpretation**:
   - Vectors are elements of vector spaces that can be added together and multiplied by scalars. 
   
   - They represent solutions to linear equations, transformations, and serve as building blocks for more complex mathematical structures. 
   
   - In linear algebra, vectors are often viewed as columns or rows of numbers that can be manipulated through matrix operations.

## **Usefulness in Deep Learning:**

1. **`Feature Representation`**:   
Each data sample is represented as a vector where each component represents a feature. For example, in image processing, a 28×28 pixel image becomes a 784-dimensional vector where each element represents a pixel intensity.

2. **`Word Embeddings`**:   
Words are converted into dense vectors that capture semantic meaning. Similar words have similar vector representations, enabling machines to understand relationships between words.

3. **`Neural Network Weights`**:   
Model parameters are stored as vectors, allowing efficient computation of gradients and parameter updates during training.

4. **`Batch Processing`**:   
Multiple data samples are processed simultaneously by organizing them into vectors and matrices, dramatically improving computational efficiency.

5. **`Gradient Computation`**:   
Gradients in neural networks are vectors pointing in the direction of steepest increase of the loss function, enabling optimization algorithms to update parameters effectively.

### **Row Vector and Column Vector:** 

**1. Horizontal Form (Row Vector):**
   - Components are arranged horizontally in a single row.

   - **Notation**:
      - **v** = [3, 4, 5]
      - **v** = (3, 4, 5)
      - **v** = ⟨3, 4, 5⟩

   - **Matrix Form**: $1×n$ matrix **(1 row, n columns)**

   - $v = [3,   4,   5]$

**2. Vertical Form (Column Vector):**  

   - Components are arranged vertically in a single column.

   - **Notation**:
```raw
                v = [3]
                    [4]
                    [5]
```

   - **Matrix Form**: $n×1$ matrix **(n rows, 1 column)**

**Key Differences:**

**1. Matrix Dimensions**:
   - **Horizontal (Row)**: Shape is $(1, n)$ - `one row`, `multiple columns`

   - **Vertical (Column)**: Shape is $(n, 1)$ - `multiple rows`, `one column`

**2. Matrix Multiplication Rules**:
```raw
    Row vector × Matrix:
      [1  2  3] × [a  b] = [1a+2c+3e  1b+2d+3f]
                  [c  d]
                  [e  f]

    Matrix × Column vector:
    [a  b] × [1] = [a×1 + b×2]
    [c  d]   [2]   [c×1 + d×2]
```

**3. Transpose Relationship**:
  - Row vector = **(Column vector)ᵀ**
  - Column vector = **(Row vector)ᵀ**

**4. PyTorch Implementation**:

In [20]:
import torch

# Horizontal form (row vector)
row_vector = torch.tensor([[3, 4, 5]])  # Shape: (1, 3)

# Vertical form (column vector)  
col_vector = torch.tensor([[3], [4], [5]])  # Shape: (3, 1)

# Converting between forms
row_to_col = row_vector.T  # or row_vector.transpose(0, 1)
col_to_row = col_vector.T

print(f"Row vector: {row_vector}")
print(f"Row shape: {row_vector.shape}")
print(f"Column vector:\n{col_vector}")
print(f"Column shape: {col_vector.shape}")

Row vector: tensor([[3, 4, 5]])
Row shape: torch.Size([1, 3])
Column vector:
tensor([[3],
        [4],
        [5]])
Column shape: torch.Size([3, 1])


**5. Geometric Interpretation**:  
Both represent the same point in space or the same direction, just written differently:
   - **`Horizontal`**: $[3, 4, 5]$ represents point $(3, 4, 5)$
   - **`Vertical`**: Same point $(3, 4, 5)$, just written as a column

**6. Usage in Different Contexts**:

**Row vectors are common in**:
   - Machine learning input data (features arranged horizontally)
   - Probability distributions
   - When vectors represent observations or samples

**Column vectors are common in**:
   - Traditional linear algebra textbooks
   - System of linear equations $(Ax = b)$
   - Geometric transformations
   - When vectors represent variables or unknowns

**7. Dot Product Calculation**:

```raw
    Row × Column: [1  2  3] × [4] = 1×4 + 2×5 + 3×6 = 32
                              [5]
                              [6]

    Column × Row: [1] × [4  5  6] = [4   5   6 ]
                  [2]               [8   10  12]
                  [3]               [12  15  18]
```

**8. Memory Layout**:  
   - **`Row vectors`**: Elements stored consecutively in memory
   - **`Column vectors`**: May have different memory stride patterns in matrices

**Important Note**:   
In most programming contexts and machine learning frameworks, the distinction matters primarily for matrix operations. For basic vector operations like addition, subtraction, and scalar multiplication, both forms behave identically - it's mainly about how we organize our data for efficient computation.

### **PyTorch Implementation Scenarios**

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np


# 1. BASIC VECTOR CREATION AND OPERATIONS 

# Creating vectors
vector_1d = torch.tensor([1, 2, 3, 4, 5])  # 1D vector
vector_2d = torch.tensor([[1, 2, 3]])      # Row vector (1x3)
vector_col = torch.tensor([[1], [2], [3]]) # Column vector (3x1)

print("1D Vector:", vector_1d)
print("2D Row Vector:", vector_2d)
print("Column Vector:\n", vector_col)
print()
print("1D Vector Shape:", vector_1d.shape)
print("2D Row Vector Shape:", vector_2d.shape)
print("Column Vector Shape:", vector_col.shape)

# Vector arithmetic
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

addition = a + b           # Element-wise addition
subtraction = a - b        # Element-wise subtraction
dot_product = torch.dot(a, b)  # Dot product
cross_product = torch.cross(a, b)  # Cross product (3D only)

print(f"\nVector Operations:")
print(f"a + b = {addition}")
print(f"a - b = {subtraction}")
print(f"a · b = {dot_product}")
print(f"a × b = {cross_product}")

1D Vector: tensor([1, 2, 3, 4, 5])
2D Row Vector: tensor([[1, 2, 3]])
Column Vector:
 tensor([[1],
        [2],
        [3]])

1D Vector Shape: torch.Size([5])
2D Row Vector Shape: torch.Size([1, 3])
Column Vector Shape: torch.Size([3, 1])

Vector Operations:
a + b = tensor([5, 7, 9])
a - b = tensor([-3, -3, -3])
a · b = 32
a × b = tensor([-3,  6, -3])


In [ ]:
# 2. FEATURE VECTORS FOR MACHINE LEARNING


# Example: Image classification features
# Simulating features extracted from an image
image_features = torch.tensor([
    0.8,   # brightness
    0.6,   # contrast
    0.3,   # red_intensity
    0.7,   # green_intensity
    0.4,   # blue_intensity
    0.9    # sharpness
])

# Batch of feature vectors (multiple samples)
batch_features = torch.tensor([
    [0.8, 0.6, 0.3, 0.7, 0.4, 0.9],  # Image 1
    [0.2, 0.8, 0.9, 0.1, 0.6, 0.3],  # Image 2
    [0.5, 0.4, 0.6, 0.8, 0.2, 0.7],  # Image 3
])

print(f"\nSingle image features:\n    {image_features}")
print(f"Single Image Features Shape: {image_features.shape}")
print()
print(f"Image Batch features:\n    {batch_features}")
print(f"Batch shape: {batch_features.shape}")


Single image features:
    tensor([0.8000, 0.6000, 0.3000, 0.7000, 0.4000, 0.9000])
Single Image Features Shape: torch.Size([6])

Image Batch features:
    tensor([[0.8000, 0.6000, 0.3000, 0.7000, 0.4000, 0.9000],
        [0.2000, 0.8000, 0.9000, 0.1000, 0.6000, 0.3000],
        [0.5000, 0.4000, 0.6000, 0.8000, 0.2000, 0.7000]])
Batch shape: torch.Size([3, 6])


In [ ]:
# 3. WORD EMBEDDINGS

# Creating word embeddings
vocab_size = 1000
embedding_dim = 100

# Embedding layer
embedding = nn.Embedding(vocab_size, embedding_dim)

# Sample word indices
word_indices = torch.tensor([1, 15, 30, 45])

# Get word vectors
word_vectors = embedding(word_indices)
print(f"\nWord embeddings shape: {word_vectors.shape}")

# Similarity between words using cosine similarity
def cosine_similarity(v1, v2):
    return torch.dot(v1, v2) / (torch.norm(v1) * torch.norm(v2))

similarity = cosine_similarity(word_vectors[0], word_vectors[1])
print(f"Cosine similarity between word 1 and word 2: {similarity:.4f}")


Word embeddings shape: torch.Size([4, 100])
Cosine similarity between word 1 and word 2: -0.1919


In [ ]:
# 4. GRADIENT VECTORS

# Simple neural network to demonstrate gradient vectors
class SimpleNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1)
    
    def forward(self, x):
        return self.linear(x)

model = SimpleNet()
x = torch.tensor([[1.0, 2.0, 3.0]], requires_grad=True)
y_true = torch.tensor([[5.0]])

# Forward pass
y_pred = model(x)
loss = F.mse_loss(y_pred, y_true)

# Backward pass - compute gradients
loss.backward()

# Access gradient vectors
print(f"\nGradient w.r.t input: {x.grad}")
print(f"Weight gradients: {model.linear.weight.grad}")
print(f"Bias gradient: {model.linear.bias.grad}")


Gradient w.r.t input: tensor([[-2.7947, -0.9862, -2.3241]])
Weight gradients: tensor([[ -5.8407, -11.6814, -17.5221]])
Bias gradient: tensor([-5.8407])


In [ ]:
# 5. VECTOR TRANSFORMATIONS


# Linear transformation using matrix multiplication
transform_matrix = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
input_vector = torch.tensor([1, 2], dtype=torch.float32)

# Apply transformation
transformed = torch.mv(transform_matrix, input_vector)
print(f"\nOriginal vector: {input_vector}")
print(f"Transformed vector: {transformed}")


Original vector: tensor([1., 2.])
Transformed vector: tensor([ 5., 11.])


In [ ]:
# 6. ATTENTION MECHANISMS (QUERY, KEY, VALUE VECTORS)


# Simplified attention mechanism
seq_length = 5
d_model = 4

# Create query, key, value vectors
queries = torch.randn(seq_length, d_model)
keys = torch.randn(seq_length, d_model)
values = torch.randn(seq_length, d_model)

# Compute attention scores
attention_scores = torch.matmul(queries, keys.transpose(-2, -1))
attention_weights = F.softmax(attention_scores, dim=-1)

# Apply attention
attended_values = torch.matmul(attention_weights, values)

print(f"\nAttention mechanism:")
print(f"Query shape: {queries.shape}")
print(f"Attention weights shape: {attention_weights.shape}")
print(f"Attended values shape: {attended_values.shape}")


Attention mechanism:
Query shape: torch.Size([5, 4])
Attention weights shape: torch.Size([5, 5])
Attended values shape: torch.Size([5, 4])


In [ ]:
# 7. LOSS FUNCTION VECTORS


# Multi-class classification scenario
num_classes = 3
batch_size = 4

# Model predictions (logits)
logits = torch.randn(batch_size, num_classes)
# True labels
targets = torch.tensor([0, 1, 2, 0])

# Convert to probability vectors
probabilities = F.softmax(logits, dim=1)
print(f"\nPrediction probabilities:\n{probabilities}")

# Cross-entropy loss
loss = F.cross_entropy(logits, targets)
print(f"Cross-entropy loss: {loss.item():.4f}")


Prediction probabilities:
tensor([[0.5455, 0.0822, 0.3723],
        [0.2699, 0.5948, 0.1352],
        [0.6584, 0.0803, 0.2613],
        [0.2992, 0.3410, 0.3597]])
Cross-entropy loss: 0.9185


In [ ]:
# 8. VECTOR NORMS AND DISTANCES


v1 = torch.tensor([3.0, 4.0])
v2 = torch.tensor([1.0, 2.0])

# Different norms
l1_norm = torch.norm(v1, p=1)      # L1 norm (Manhattan distance)
l2_norm = torch.norm(v1, p=2)      # L2 norm (Euclidean distance)
max_norm = torch.norm(v1, p=float('inf'))  # Max norm

# Distance between vectors
euclidean_distance = torch.norm(v1 - v2)
manhattan_distance = torch.norm(v1 - v2, p=1)

print(f"\nVector norms and distances:")
print(f"L1 norm of v1: {l1_norm}")
print(f"L2 norm of v1: {l2_norm}")
print(f"Max norm of v1: {max_norm}")
print(f"Euclidean distance: {euclidean_distance}")
print(f"Manhattan distance: {manhattan_distance}")


Vector norms and distances:
L1 norm of v1: 7.0
L2 norm of v1: 5.0
Max norm of v1: 4.0
Euclidean distance: 2.8284270763397217
Manhattan distance: 4.0


In [ ]:
# 9. VECTOR NORMALIZATION


# Unit vector (normalized)
unit_vector = v1 / torch.norm(v1)
print(f"\nOriginal vector: {v1}")
print(f"Unit vector: {unit_vector}")
print(f"Unit vector norm: {torch.norm(unit_vector)}")

# Batch normalization on vectors
batch_vectors = torch.randn(10, 5)  # 10 vectors of dimension 5
normalized_batch = F.normalize(batch_vectors, p=2, dim=1)
print(f"\nBatch vectors shape: {batch_vectors.shape}")
print(f"Normalized batch shape: {normalized_batch.shape}")


Original vector: tensor([3., 4.])
Unit vector: tensor([0.6000, 0.8000])
Unit vector norm: 1.0

Batch vectors shape: torch.Size([10, 5])
Normalized batch shape: torch.Size([10, 5])


In [19]:
# 10. VECTOR CONCATENATION AND RESHAPING


# Concatenating vectors
v_a = torch.tensor([1, 2, 3])
v_b = torch.tensor([4, 5, 6])
v_c = torch.tensor([7, 8, 9])

# Concatenate along dimension 0
concatenated = torch.cat([v_a, v_b, v_c], dim=0)
print(f"\nConcatenated vector: {concatenated}")

# Stack vectors (creates new dimension)
stacked = torch.stack([v_a, v_b, v_c], dim=0)
print(f"Stacked vectors shape: {stacked.shape}")

# Reshape vector
reshaped = concatenated.view(3, 3)
print(f"Reshaped to matrix:\n{reshaped}")


Concatenated vector: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Stacked vectors shape: torch.Size([3, 3])
Reshaped to matrix:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


### **Properties of Vectors:**

**1. Addition and Subtraction**:     
  Vectors can be added or subtracted element-wise. For vectors **$a$** = $[1, 2, 3]$ and **$b$** = $[4, 5, 6]$, their sum is **$a$** + **$b$** = $[5, 7, 9]$. This operation is commutative (**$a$** + **$b$** = **$b$** + **$a$**) and associative ((**$a$** + **$b$**) + **$c$** = **$a$** + (**$b$** + **$c$**)).

**2. Scalar Multiplication**:   
Multiplying a vector by a scalar scales all components uniformly. If **$v$** = $[2, 3, 4]$ and scalar $c = 3$, then $c$**$v$** = $[6, 9, 12]$. This operation preserves the direction of the vector but changes its magnitude.

**3. Dot Product (Inner Product)**:   
The dot product of two vectors produces a scalar value. For **$a$** = $[1, 2, 3]$ and **$b$** = $[4, 5, 6]$, the dot product is **$a$** · **$b$** = $1×4 + 2×5 + 3×6 = 32$. This operation is commutative and measures the similarity between vectors.

**4. Cross Product**:   
In 3D space, the cross product of two vectors produces a third vector perpendicular to both original vectors. For **$a$** = $[1, 2, 3]$ and **$b$** = $[4, 5, 6]$, **$a$** × **$b$** = $[2×6 - 3×5, 3×4 - 1×6, 1×5 - 2×4] = [-3, 6, -3]$.

**5. Magnitude (Norm)**:   
The magnitude of a vector represents its length. For vector **$v$** = $[3, 4]$, the magnitude is ||**$v$**|| = $√(3² + 4²) = 5$. Different norms exist: `L1 norm (Manhattan distance)`, `L2 norm (Euclidean distance)`, and `infinity norm (maximum component)`.

**6. Unit Vectors**:   
A unit vector has magnitude 1 and represents pure direction. Any vector can be normalized to create a unit vector by dividing by its magnitude: **$û$** = **$v$**/||**$v$**||.

**7. Linear Independence**:   
A set of vectors is linearly independent if none can be expressed as a linear combination of the others. This property is crucial for determining the dimension of vector spaces and the uniqueness of solutions to linear systems.

**8. Orthogonality**:   
Two vectors are orthogonal if their dot product is zero, meaning they're perpendicular. Orthogonal vectors are particularly useful in machine learning for creating uncorrelated features and in optimization algorithms.

**9. Span**:   
The span of a set of vectors is the collection of all possible linear combinations of those vectors. It represents the space that can be reached by combining the vectors with different scalar weights.

**10. Dimensionality**:   
The number of components in a vector determines its dimensionality. A 3D vector has three components, while high-dimensional vectors in machine learning can have thousands or millions of components.

**11. Basis Vectors**:   
A basis is a set of linearly independent vectors that span the entire vector space. Any vector in the space can be uniquely expressed as a linear combination of basis vectors.

**12. Distance and Similarity**:   
Vectors can be compared using various distance metrics. Euclidean distance measures straight-line distance, while cosine similarity measures the angle between vectors, making it useful for comparing directions regardless of magnitude.

---
---
---

## **3. Matrix:**

> ![](https://image.slidesharecdn.com/matrix-130924233933-phpapp01/95/linear-algebra-and-matrix-3-638.jpg?cb=1380066049)

> ![](https://th.bing.com/th/id/R.efe53963822fb24b15835f0b93f3aaa3?rik=jDrYL3UYAYtd6A&pid=ImgRaw&r=0)

In linear algebra, a **`matrix`** is a rectangular array or grid of numbers, symbols, or expressions arranged in rows and columns. It's a fundamental concept used to represent and manipulate data in a structured way.

Matrices are typically denoted by a bold capital letter, such as **$A$**. The elements within the matrix are represented by lowercase letters with subscripts indicating their position. For an element in the *i*-th row and *j*-th column of a matrix **$A$**, the notation is $a\_{ij}$.

An $m\times n$ matrix has *m* rows and *n* columns. For example, a 2x3 matrix **A** is written as:

$A = \begin{pmatrix} 
a_{11} & a_{12} & a_{13} \\ 
a_{21} & a_{22} & a_{23} 
\end{pmatrix}$

### **Matrices in Deep Learning 🧠:**

Matrices are at the heart of deep learning because they provide a concise and efficient way to represent and process the vast amounts of data that neural networks handle.

At its core, a neural network is a series of mathematical operations, and matrices are the perfect tool for performing these computations on a large scale. Here’s a breakdown of how matrices are integral to deep learning:

  * **`Data Representation`**:   
  Datasets, whether they consist of images, text, or tabular data, are converted into matrices. For instance, a grayscale image can be represented as a matrix where each element corresponds to the pixel intensity. A batch of images is then represented as a higher-dimensional matrix.

  * **`Model Parameters`**:   
  The `"knowledge"` a neural network learns is stored in its parameters, which are organized into `matrices`. The connections between neurons in different layers of a neural network are represented by a `weight matrix`. As the network trains, these weights are adjusted through a process called backpropagation, which heavily relies on `matrix calculus`.

  * **`Linear Transformations`**:   
  Each layer in a neural network applies a `linear transformation` to the data it receives from the previous layer. This transformation is a `matrix-vector` or `matrix-matrix` multiplication. For a given layer, the input data (represented as a `vector` or `matrix`) is multiplied by the layer's `weight matrix`.

  * **`Computational Efficiency`**:   
  Modern computing hardware, especially Graphics Processing Units $(GPUs)$ and Tensor Processing Units $(TPUs)$, are highly optimized for matrix operations. Performing calculations on large matrices is significantly faster than iterating through individual data points, which is crucial for training deep learning models on massive datasets.

## **Forming Matrices in NumPy and PyTorch:**

1. NumPy is a fundamental package for scientific computing in Python. Creating a matrix is straightforward:

In [21]:
import numpy as np

# Create a 3x3 matrix from a list of lists
numpy_matrix = np.array([[1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9]])

print(numpy_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2. PyTorch is a popular open-source machine learning library. Its core data structure is the tensor, which can be used to represent matrices.

In [22]:
import torch

# Create a 3x3 matrix (tensor)
pytorch_matrix = torch.tensor([[1, 2, 3],
                               [4, 5, 6],
                               [7, 8, 9]])

print(pytorch_matrix)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


### **Matrix vs. Array vs. Tensor: What's the Difference?**

While these terms are often used interchangeably in programming contexts, they have distinct mathematical and conceptual meanings.

| Term    | Description                                                                                                                               |
| :------ | :---------------------------------------------------------------------------------------------------------------------------------------- |
| **Array** | In programming, an **array** is a data structure that stores a collection of elements. It can be one-dimensional, two-dimensional (like a matrix), or multi-dimensional. It's a more general concept. |
| **Matrix** | In linear algebra, a **matrix** is a two-dimensional array of numbers that has specific mathematical properties and operations defined on it, such as matrix multiplication and inversion. |
| **Tensor** | A **tensor** is a generalization of scalars, vectors, and matrices to higher dimensions. A scalar is a rank-0 tensor, a vector is a rank-1 tensor, and a matrix is a rank-2 tensor. Tensors are the fundamental data structure in deep learning frameworks like PyTorch and TensorFlow. |

A `matrix is a specific type of array` with a rich set of mathematical rules. A `tensor is a further generalization that can encompass data of any dimensionality`.

### **Properties of Matrices in Linear Algebra:**

Matrices have several important properties that govern their behavior in mathematical operations. For matrices **$A$**, **$B$**, and **4** of the same size, and a scalar *$k$*:

#### 1. **Addition:**

  * **Commutative Property**: $A + B = B + A$
  * **Associative Property**: $(A + B) + C = A + (B + C)$
  * **Additive Identity**: There exists a zero matrix **$0$** such that $A + 0 = A$.
  * **Additive Inverse**: For every matrix **$A$**, there exists a matrix **$-A$** such that $A + (-A) = 0$.

#### 2. **Scalar Multiplication:**

  * **Distributive Property**: $k(A + B) = kA + kB$
  * **Distributive Property**: $(k + l)A = kA + lA$ (where *$l$* is also a scalar)
  * **Associative Property**: $(kl)A = k(lA)$

#### 3. **Matrix Multiplication:**

  * **Associative Property**: $(AB)C = A(BC)$
  * **Distributive Property**: $A(B + C) = AB + AC$ and $(A + B)C = AC + BC$
  * **Multiplicative Identity**: For a square matrix **A**, there exists an identity matrix **I** of the same size such that $AI = IA = A$.
  * **Not Commutative**: In general, $AB \neq BA$. The order of multiplication matters.

#### 4. **Transpose:**

The transpose of a matrix **A**, denoted as $A^T$, is obtained by swapping its rows and columns.

  * **Transpose of a Transpose**: $(A^T)^T = A$
  * **Transpose of a Sum**: $(A + B)^T = A^T + B^T$
  * **Transpose of a Product**: $(AB)^T = B^T A^T$